import { VirtualElement } from "./VirtualElement";
export function a(attributes, children) { return new VirtualElement("a", attributes, children); }
export function applet(attributes, children) { return new VirtualElement("applet", attributes, children); }
export function area(attributes, children) { return new VirtualElement("area", attributes, children); }
export function audio(attributes, children) { return new VirtualElement("audio", attributes, children); }
export function base(attributes, children) { return new VirtualElement("base", attributes, children); }
export function basefont(attributes, children) { return new VirtualElement("basefont", attributes, children); }
export function blockquote(attributes, children) { return new VirtualElement("blockquote", attributes, children); }
export function body(attributes, children) { return new VirtualElement("body", attributes, children); }
export function br(attributes, children) { return new VirtualElement("br", attributes, children); }
export function button(attributes, children) { return new VirtualElement("button", attributes, children); }
export function canvas(attributes, children) { return new VirtualElement("canvas", attributes, children); }
export function caption(attributes, children) { return new VirtualElement("caption", attributes, children); }
export function col(attributes, children) { return new VirtualElement("col", attributes, children); }
export function colgroup(attributes, children) { return new VirtualElement("colgroup", attributes, children); }
export function data(attributes, children) { return new VirtualElement("data", attributes, children); }
export function datalist(attributes, children) { return new VirtualElement("datalist", attributes, children); }
export function del(attributes, children) { return new VirtualElement("del", attributes, children); }
export function dir(attributes, children) { return new VirtualElement("dir", attributes, children); }
export function div(attributes, children) { return new VirtualElement("div", attributes, children); }
export function dl(attributes, children) { return new VirtualElement("dl", attributes, children); }
export function embed(attributes, children) { return new VirtualElement("embed", attributes, children); }
export function fieldset(attributes, children) { return new VirtualElement("fieldset", attributes, children); }
export function font(attributes, children) { return new VirtualElement("font", attributes, children); }
export function form(attributes, children) { return new VirtualElement("form", attributes, children); }
export function frame(attributes, children) { return new VirtualElement("frame", attributes, children); }
export function frameset(attributes, children) { return new VirtualElement("frameset", attributes, children); }
export function h1(attributes, children) { return new VirtualElement("h1", attributes, children); }
export function h2(attributes, children) { return new VirtualElement("h2", attributes, children); }
export function h3(attributes, children) { return new VirtualElement("h3", attributes, children); }
export function h4(attributes, children) { return new VirtualElement("h4", attributes, children); }
export function h5(attributes, children) { return new VirtualElement("h5", attributes, children); }
export function h6(attributes, children) { return new VirtualElement("h6", attributes, children); }
export function head(attributes, children) { return new VirtualElement("head", attributes, children); }
export function hr(attributes, children) { return new VirtualElement("hr", attributes, children); }
export function html(attributes, children) { return new VirtualElement("html", attributes, children); }
export function iframe(attributes, children) { return new VirtualElement("iframe", attributes, children); }
export function img(attributes, children) { return new VirtualElement("img", attributes, children); }
export function input(attributes, children) { return new VirtualElement("input", attributes, children); }
export function ins(attributes, children) { return new VirtualElement("ins", attributes, children); }
export function isindex(attributes, children) { return new VirtualElement("isindex", attributes, children); }
export function label(attributes, children) { return new VirtualElement("label", attributes, children); }
export function legend(attributes, children) { return new VirtualElement("legend", attributes, children); }
export function li(attributes, children) { return new VirtualElement("li", attributes, children); }
export function link(attributes, children) { return new VirtualElement("link", attributes, children); }
export function listing(attributes, children) { return new VirtualElement("listing", attributes, children); }
export function map(attributes, children) { return new VirtualElement("map", attributes, children); }
export function marquee(attributes, children) { return new VirtualElement("marquee", attributes, children); }
export function menu(attributes, children) { return new VirtualElement("menu", attributes, children); }
export function meta(attributes, children) { return new VirtualElement("meta", attributes, children); }
export function meter(attributes, children) { return new VirtualElement("meter", attributes, children); }
export function nextid(attributes, children) { return new VirtualElement("nextid", attributes, children); }
export function object(attributes, children) { return new VirtualElement("object", attributes, children); }
export function ol(attributes, children) { return new VirtualElement("ol", attributes, children); }
export function optgroup(attributes, children) { return new VirtualElement("optgroup", attributes, children); }
export function option(attributes, children) { return new VirtualElement("option", attributes, children); }
export function output(attributes, children) { return new VirtualElement("output", attributes, children); }
export function p(attributes, children) { return new VirtualElement("p", attributes, children); }
export function param(attributes, children) { return new VirtualElement("param", attributes, children); }
export function picture(attributes, children) { return new VirtualElement("picture", attributes, children); }
export function pre(attributes, children) { return new VirtualElement("pre", attributes, children); }
export function progress(attributes, children) { return new VirtualElement("progress", attributes, children); }
export function q(attributes, children) { return new VirtualElement("q", attributes, children); }
export function script(attributes, children) { return new VirtualElement("script", attributes, children); }
export function select(attributes, children) { return new VirtualElement("select", attributes, children); }
export function source(attributes, children) { return new VirtualElement("source", attributes, children); }
export function span(attributes, children) { return new VirtualElement("span", attributes, children); }
export function style(attributes, children) { return new VirtualElement("style", attributes, children); }
export function table(attributes, children) { return new VirtualElement("table", attributes, children); }
export function tbody(attributes, children) { return new VirtualElement("tbody", attributes, children); }
export function td(attributes, children) { return new VirtualElement("td", attributes, children); }
export function template(attributes, children) { return new VirtualElement("template", attributes, children); }
export function textarea(attributes, children) { return new VirtualElement("textarea", attributes, children); }
export function tfoot(attributes, children) { return new VirtualElement("tfoot", attributes, children); }
export function th(attributes, children) { return new VirtualElement("th", attributes, children); }
export function thead(attributes, children) { return new VirtualElement("thead", attributes, children); }
export function time(attributes, children) { return new VirtualElement("time", attributes, children); }
export function title(attributes, children) { return new VirtualElement("title", attributes, children); }
export function tr(attributes, children) { return new VirtualElement("tr", attributes, children); }
export function track(attributes, children) { return new VirtualElement("track", attributes, children); }
export function ul(attributes, children) { return new VirtualElement("ul", attributes, children); }
export function video(attributes, children) { return new VirtualElement("video", attributes, children); }
export function xmp(attributes, children) { return new VirtualElement("xmp", attributes, children); }
