
var map = {
    
    "a": "HTMLAnchorElement",
    "applet": "HTMLAppletElement",
    "area": "HTMLAreaElement",
    "audio": "HTMLAudioElement",
    "base": "HTMLBaseElement",
    "basefont": "HTMLBaseFontElement",
    "blockquote": "HTMLQuoteElement",
    "body": "HTMLBodyElement",
    "br": "HTMLBRElement",
    "button": "HTMLButtonElement",
    "canvas": "HTMLCanvasElement",
    "caption": "HTMLTableCaptionElement",
    "col": "HTMLTableColElement",
    "colgroup": "HTMLTableColElement",
    "data": "HTMLDataElement",
    "datalist": "HTMLDataListElement",
    "del": "HTMLModElement",
    "dir": "HTMLDirectoryElement",
    "div": "HTMLDivElement",
    "dl": "HTMLDListElement",
    "embed": "HTMLEmbedElement",
    "fieldset": "HTMLFieldSetElement",
    "font": "HTMLFontElement",
    "form": "HTMLFormElement",
    "frame": "HTMLFrameElement",
    "frameset": "HTMLFrameSetElement",
    "h1": "HTMLHeadingElement",
    "h2": "HTMLHeadingElement",
    "h3": "HTMLHeadingElement",
    "h4": "HTMLHeadingElement",
    "h5": "HTMLHeadingElement",
    "h6": "HTMLHeadingElement",
    "head": "HTMLHeadElement",
    "hr": "HTMLHRElement",
    "html": "HTMLHtmlElement",
    "iframe": "HTMLIFrameElement",
    "img": "HTMLImageElement",
    "input": "HTMLInputElement",
    "ins": "HTMLModElement",
    "isindex": "HTMLUnknownElement",
    "label": "HTMLLabelElement",
    "legend": "HTMLLegendElement",
    "li": "HTMLLIElement",
    "link": "HTMLLinkElement",
    "listing": "HTMLPreElement",
    "map": "HTMLMapElement",
    "marquee": "HTMLMarqueeElement",
    "menu": "HTMLMenuElement",
    "meta": "HTMLMetaElement",
    "meter": "HTMLMeterElement",
    "nextid": "HTMLUnknownElement",
    "object": "HTMLObjectElement",
    "ol": "HTMLOListElement",
    "optgroup": "HTMLOptGroupElement",
    "option": "HTMLOptionElement",
    "output": "HTMLOutputElement",
    "p": "HTMLParagraphElement",
    "param": "HTMLParamElement",
    "picture": "HTMLPictureElement",
    "pre": "HTMLPreElement",
    "progress": "HTMLProgressElement",
    "q": "HTMLQuoteElement",
    "script": "HTMLScriptElement",
    "select": "HTMLSelectElement",
    "source": "HTMLSourceElement",
    "span": "HTMLSpanElement",
    "style": "HTMLStyleElement",
    "table": "HTMLTableElement",
    "tbody": "HTMLTableSectionElement",
    "td": "HTMLTableDataCellElement",
    "template": "HTMLTemplateElement",
    "textarea": "HTMLTextAreaElement",
    "tfoot": "HTMLTableSectionElement",
    "th": "HTMLTableHeaderCellElement",
    "thead": "HTMLTableSectionElement",
    "time": "HTMLTimeElement",
    "title": "HTMLTitleElement",
    "tr": "HTMLTableRowElement",
    "track": "HTMLTrackElement",
    "ul": "HTMLUListElement",
    "video": "HTMLVideoElement",
    "x-ms-webview": "MSHTMLWebViewElement",
    "xmp": "HTMLPreElement",
}

for (key in map){
 console.log("export function " +key+ "(attributes?: Attribute<" + map[key] + "> | null , children?: (VirtualElement| null)[] | null | string ){ return new VirtualElement(\""+key+"\", attributes, children);}")
}

